// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/crowdsound_admin_service.proto

#ifndef PROTOBUF_proto_2fcrowdsound_5fadmin_5fservice_2eproto__INCLUDED
#define PROTOBUF_proto_2fcrowdsound_5fadmin_5fservice_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace CrowdSound {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_proto_2fcrowdsound_5fadmin_5fservice_2eproto();
void protobuf_AssignDesc_proto_2fcrowdsound_5fadmin_5fservice_2eproto();
void protobuf_ShutdownFile_proto_2fcrowdsound_5fadmin_5fservice_2eproto();

class GetDBStatsRequest;
class GetDBStatsResponse;
class GetSettingsRequest;
class GetSettingsResponse;
class GetVersionInfoRequest;
class GetVersionInfoResponse;
class SetSettingRequest;
class SetSettingResponse;
class SkipRequest;
class SkipResponse;
class SkipStatusRequest;
class SkipStatusResponse;

// ===================================================================

class SkipStatusRequest : public ::google::protobuf::Message {
 public:
  SkipStatusRequest();
  virtual ~SkipStatusRequest();

  SkipStatusRequest(const SkipStatusRequest& from);

  inline SkipStatusRequest& operator=(const SkipStatusRequest& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SkipStatusRequest& default_instance();

  void Swap(SkipStatusRequest* other);

  // implements Message ----------------------------------------------

  inline SkipStatusRequest* New() const { return New(NULL); }

  SkipStatusRequest* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SkipStatusRequest& from);
  void MergeFrom(const SkipStatusRequest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(SkipStatusRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:CrowdSound.SkipStatusRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_proto_2fcrowdsound_5fadmin_5fservice_2eproto();
  friend void protobuf_AssignDesc_proto_2fcrowdsound_5fadmin_5fservice_2eproto();
  friend void protobuf_ShutdownFile_proto_2fcrowdsound_5fadmin_5fservice_2eproto();

  void InitAsDefaultInstance();
  static SkipStatusRequest* default_instance_;
};
// -------------------------------------------------------------------

class SkipStatusResponse : public ::google::protobuf::Message {
 public:
  SkipStatusResponse();
  virtual ~SkipStatusResponse();

  SkipStatusResponse(const SkipStatusResponse& from);

  inline SkipStatusResponse& operator=(const SkipStatusResponse& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SkipStatusResponse& default_instance();

  void Swap(SkipStatusResponse* other);

  // implements Message ----------------------------------------------

  inline SkipStatusResponse* New() const { return New(NULL); }

  SkipStatusResponse* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SkipStatusResponse& from);
  void MergeFrom(const SkipStatusResponse& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(SkipStatusResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 votes_to_skip = 1;
  void clear_votes_to_skip();
  static const int kVotesToSkipFieldNumber = 1;
  ::google::protobuf::int32 votes_to_skip() const;
  void set_votes_to_skip(::google::protobuf::int32 value);

  // optional int32 total_users = 2;
  void clear_total_users();
  static const int kTotalUsersFieldNumber = 2;
  ::google::protobuf::int32 total_users() const;
  void set_total_users(::google::protobuf::int32 value);

  // optional float threshold = 3;
  void clear_threshold();
  static const int kThresholdFieldNumber = 3;
  float threshold() const;
  void set_threshold(float value);

  // @@protoc_insertion_point(class_scope:CrowdSound.SkipStatusResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::int32 votes_to_skip_;
  ::google::protobuf::int32 total_users_;
  float threshold_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_proto_2fcrowdsound_5fadmin_5fservice_2eproto();
  friend void protobuf_AssignDesc_proto_2fcrowdsound_5fadmin_5fservice_2eproto();
  friend void protobuf_ShutdownFile_proto_2fcrowdsound_5fadmin_5fservice_2eproto();

  void InitAsDefaultInstance();
  static SkipStatusResponse* default_instance_;
};
// -------------------------------------------------------------------

class SkipRequest : public ::google::protobuf::Message {
 public:
  SkipRequest();
  virtual ~SkipRequest();

  SkipRequest(const SkipRequest& from);

  inline SkipRequest& operator=(const SkipRequest& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SkipRequest& default_instance();

  void Swap(SkipRequest* other);

  // implements Message ----------------------------------------------

  inline SkipRequest* New() const { return New(NULL); }

  SkipRequest* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SkipRequest& from);
  void MergeFrom(const SkipRequest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(SkipRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:CrowdSound.SkipRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_proto_2fcrowdsound_5fadmin_5fservice_2eproto();
  friend void protobuf_AssignDesc_proto_2fcrowdsound_5fadmin_5fservice_2eproto();
  friend void protobuf_ShutdownFile_proto_2fcrowdsound_5fadmin_5fservice_2eproto();

  void InitAsDefaultInstance();
  static SkipRequest* default_instance_;
};
// -------------------------------------------------------------------

class SkipResponse : public ::google::protobuf::Message {
 public:
  SkipResponse();
  virtual ~SkipResponse();

  SkipResponse(const SkipResponse& from);

  inline SkipResponse& operator=(const SkipResponse& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SkipResponse& default_instance();

  void Swap(SkipResponse* other);

  // implements Message ----------------------------------------------

  inline SkipResponse* New() const { return New(NULL); }

  SkipResponse* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SkipResponse& from);
  void MergeFrom(const SkipResponse& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(SkipResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:CrowdSound.SkipResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_proto_2fcrowdsound_5fadmin_5fservice_2eproto();
  friend void protobuf_AssignDesc_proto_2fcrowdsound_5fadmin_5fservice_2eproto();
  friend void protobuf_ShutdownFile_proto_2fcrowdsound_5fadmin_5fservice_2eproto();

  void InitAsDefaultInstance();
  static SkipResponse* default_instance_;
};
// -------------------------------------------------------------------

class GetSettingsRequest : public ::google::protobuf::Message {
 public:
  GetSettingsRequest();
  virtual ~GetSettingsRequest();

  GetSettingsRequest(const GetSettingsRequest& from);

  inline GetSettingsRequest& operator=(const GetSettingsRequest& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const GetSettingsRequest& default_instance();

  void Swap(GetSettingsRequest* other);

  // implements Message ----------------------------------------------

  inline GetSettingsRequest* New() const { return New(NULL); }

  GetSettingsRequest* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const GetSettingsRequest& from);
  void MergeFrom(const GetSettingsRequest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(GetSettingsRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:CrowdSound.GetSettingsRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_proto_2fcrowdsound_5fadmin_5fservice_2eproto();
  friend void protobuf_AssignDesc_proto_2fcrowdsound_5fadmin_5fservice_2eproto();
  friend void protobuf_ShutdownFile_proto_2fcrowdsound_5fadmin_5fservice_2eproto();

  void InitAsDefaultInstance();
  static GetSettingsRequest* default_instance_;
};
// -------------------------------------------------------------------

class GetSettingsResponse : public ::google::protobuf::Message {
 public:
  GetSettingsResponse();
  virtual ~GetSettingsResponse();

  GetSettingsResponse(const GetSettingsResponse& from);

  inline GetSettingsResponse& operator=(const GetSettingsResponse& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const GetSettingsResponse& default_instance();

  void Swap(GetSettingsResponse* other);

  // implements Message ----------------------------------------------

  inline GetSettingsResponse* New() const { return New(NULL); }

  GetSettingsResponse* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const GetSettingsResponse& from);
  void MergeFrom(const GetSettingsResponse& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(GetSettingsResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional bool filter_buffered = 1;
  void clear_filter_buffered();
  static const int kFilterBufferedFieldNumber = 1;
  bool filter_buffered() const;
  void set_filter_buffered(bool value);

  // optional int32 inactivity_threshold = 2;
  void clear_inactivity_threshold();
  static const int kInactivityThresholdFieldNumber = 2;
  ::google::protobuf::int32 inactivity_threshold() const;
  void set_inactivity_threshold(::google::protobuf::int32 value);

  // optional int32 result_limit = 3;
  void clear_result_limit();
  static const int kResultLimitFieldNumber = 3;
  ::google::protobuf::int32 result_limit() const;
  void set_result_limit(::google::protobuf::int32 value);

  // optional string session_name = 4;
  void clear_session_name();
  static const int kSessionNameFieldNumber = 4;
  const ::std::string& session_name() const;
  void set_session_name(const ::std::string& value);
  void set_session_name(const char* value);
  void set_session_name(const char* value, size_t size);
  ::std::string* mutable_session_name();
  ::std::string* release_session_name();
  void set_allocated_session_name(::std::string* session_name);

  // optional int32 queue_size = 5;
  void clear_queue_size();
  static const int kQueueSizeFieldNumber = 5;
  ::google::protobuf::int32 queue_size() const;
  void set_queue_size(::google::protobuf::int32 value);

  // optional int32 trending_artists_size = 6;
  void clear_trending_artists_size();
  static const int kTrendingArtistsSizeFieldNumber = 6;
  ::google::protobuf::int32 trending_artists_size() const;
  void set_trending_artists_size(::google::protobuf::int32 value);

  // optional float skip_threshold = 7;
  void clear_skip_threshold();
  static const int kSkipThresholdFieldNumber = 7;
  float skip_threshold() const;
  void set_skip_threshold(float value);

  // optional float count_weight = 8;
  void clear_count_weight();
  static const int kCountWeightFieldNumber = 8;
  float count_weight() const;
  void set_count_weight(float value);

  // optional float vote_weight = 9;
  void clear_vote_weight();
  static const int kVoteWeightFieldNumber = 9;
  float vote_weight() const;
  void set_vote_weight(float value);

  // optional float genre_weight = 10;
  void clear_genre_weight();
  static const int kGenreWeightFieldNumber = 10;
  float genre_weight() const;
  void set_genre_weight(float value);

  // optional float artist_weight = 11;
  void clear_artist_weight();
  static const int kArtistWeightFieldNumber = 11;
  float artist_weight() const;
  void set_artist_weight(float value);

  // optional float played_again_mult = 12;
  void clear_played_again_mult();
  static const int kPlayedAgainMultFieldNumber = 12;
  float played_again_mult() const;
  void set_played_again_mult(float value);

  // optional float min_repeat_window = 13;
  void clear_min_repeat_window();
  static const int kMinRepeatWindowFieldNumber = 13;
  float min_repeat_window() const;
  void set_min_repeat_window(float value);

  // @@protoc_insertion_point(class_scope:CrowdSound.GetSettingsResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  bool filter_buffered_;
  ::google::protobuf::int32 inactivity_threshold_;
  ::google::protobuf::internal::ArenaStringPtr session_name_;
  ::google::protobuf::int32 result_limit_;
  ::google::protobuf::int32 queue_size_;
  ::google::protobuf::int32 trending_artists_size_;
  float skip_threshold_;
  float count_weight_;
  float vote_weight_;
  float genre_weight_;
  float artist_weight_;
  float played_again_mult_;
  float min_repeat_window_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_proto_2fcrowdsound_5fadmin_5fservice_2eproto();
  friend void protobuf_AssignDesc_proto_2fcrowdsound_5fadmin_5fservice_2eproto();
  friend void protobuf_ShutdownFile_proto_2fcrowdsound_5fadmin_5fservice_2eproto();

  void InitAsDefaultInstance();
  static GetSettingsResponse* default_instance_;
};
// -------------------------------------------------------------------

class SetSettingRequest : public ::google::protobuf::Message {
 public:
  SetSettingRequest();
  virtual ~SetSettingRequest();

  SetSettingRequest(const SetSettingRequest& from);

  inline SetSettingRequest& operator=(const SetSettingRequest& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SetSettingRequest& default_instance();

  enum ValueCase {
    kBoolVal = 2,
    kStrVal = 3,
    kIntVal = 4,
    kFloatVal = 5,
    VALUE_NOT_SET = 0,
  };

  void Swap(SetSettingRequest* other);

  // implements Message ----------------------------------------------

  inline SetSettingRequest* New() const { return New(NULL); }

  SetSettingRequest* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SetSettingRequest& from);
  void MergeFrom(const SetSettingRequest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(SetSettingRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string key = 1;
  void clear_key();
  static const int kKeyFieldNumber = 1;
  const ::std::string& key() const;
  void set_key(const ::std::string& value);
  void set_key(const char* value);
  void set_key(const char* value, size_t size);
  ::std::string* mutable_key();
  ::std::string* release_key();
  void set_allocated_key(::std::string* key);

  // optional bool bool_val = 2;
  private:
  bool has_bool_val() const;
  public:
  void clear_bool_val();
  static const int kBoolValFieldNumber = 2;
  bool bool_val() const;
  void set_bool_val(bool value);

  // optional string str_val = 3;
  private:
  bool has_str_val() const;
  public:
  void clear_str_val();
  static const int kStrValFieldNumber = 3;
  const ::std::string& str_val() const;
  void set_str_val(const ::std::string& value);
  void set_str_val(const char* value);
  void set_str_val(const char* value, size_t size);
  ::std::string* mutable_str_val();
  ::std::string* release_str_val();
  void set_allocated_str_val(::std::string* str_val);

  // optional int32 int_val = 4;
  private:
  bool has_int_val() const;
  public:
  void clear_int_val();
  static const int kIntValFieldNumber = 4;
  ::google::protobuf::int32 int_val() const;
  void set_int_val(::google::protobuf::int32 value);

  // optional float float_val = 5;
  private:
  bool has_float_val() const;
  public:
  void clear_float_val();
  static const int kFloatValFieldNumber = 5;
  float float_val() const;
  void set_float_val(float value);

  ValueCase value_case() const;
  // @@protoc_insertion_point(class_scope:CrowdSound.SetSettingRequest)
 private:
  inline void set_has_bool_val();
  inline void set_has_str_val();
  inline void set_has_int_val();
  inline void set_has_float_val();

  inline bool has_value() const;
  void clear_value();
  inline void clear_has_value();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::internal::ArenaStringPtr key_;
  union ValueUnion {
    ValueUnion() {}
    bool bool_val_;
    ::google::protobuf::internal::ArenaStringPtr str_val_;
    ::google::protobuf::int32 int_val_;
    float float_val_;
  } value_;
  mutable int _cached_size_;
  ::google::protobuf::uint32 _oneof_case_[1];

  friend void  protobuf_AddDesc_proto_2fcrowdsound_5fadmin_5fservice_2eproto();
  friend void protobuf_AssignDesc_proto_2fcrowdsound_5fadmin_5fservice_2eproto();
  friend void protobuf_ShutdownFile_proto_2fcrowdsound_5fadmin_5fservice_2eproto();

  void InitAsDefaultInstance();
  static SetSettingRequest* default_instance_;
};
// -------------------------------------------------------------------

class SetSettingResponse : public ::google::protobuf::Message {
 public:
  SetSettingResponse();
  virtual ~SetSettingResponse();

  SetSettingResponse(const SetSettingResponse& from);

  inline SetSettingResponse& operator=(const SetSettingResponse& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SetSettingResponse& default_instance();

  void Swap(SetSettingResponse* other);

  // implements Message ----------------------------------------------

  inline SetSettingResponse* New() const { return New(NULL); }

  SetSettingResponse* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SetSettingResponse& from);
  void MergeFrom(const SetSettingResponse& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(SetSettingResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:CrowdSound.SetSettingResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_proto_2fcrowdsound_5fadmin_5fservice_2eproto();
  friend void protobuf_AssignDesc_proto_2fcrowdsound_5fadmin_5fservice_2eproto();
  friend void protobuf_ShutdownFile_proto_2fcrowdsound_5fadmin_5fservice_2eproto();

  void InitAsDefaultInstance();
  static SetSettingResponse* default_instance_;
};
// -------------------------------------------------------------------

class GetVersionInfoRequest : public ::google::protobuf::Message {
 public:
  GetVersionInfoRequest();
  virtual ~GetVersionInfoRequest();

  GetVersionInfoRequest(const GetVersionInfoRequest& from);

  inline GetVersionInfoRequest& operator=(const GetVersionInfoRequest& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const GetVersionInfoRequest& default_instance();

  void Swap(GetVersionInfoRequest* other);

  // implements Message ----------------------------------------------

  inline GetVersionInfoRequest* New() const { return New(NULL); }

  GetVersionInfoRequest* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const GetVersionInfoRequest& from);
  void MergeFrom(const GetVersionInfoRequest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(GetVersionInfoRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:CrowdSound.GetVersionInfoRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_proto_2fcrowdsound_5fadmin_5fservice_2eproto();
  friend void protobuf_AssignDesc_proto_2fcrowdsound_5fadmin_5fservice_2eproto();
  friend void protobuf_ShutdownFile_proto_2fcrowdsound_5fadmin_5fservice_2eproto();

  void InitAsDefaultInstance();
  static GetVersionInfoRequest* default_instance_;
};
// -------------------------------------------------------------------

class GetVersionInfoResponse : public ::google::protobuf::Message {
 public:
  GetVersionInfoResponse();
  virtual ~GetVersionInfoResponse();

  GetVersionInfoResponse(const GetVersionInfoResponse& from);

  inline GetVersionInfoResponse& operator=(const GetVersionInfoResponse& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const GetVersionInfoResponse& default_instance();

  void Swap(GetVersionInfoResponse* other);

  // implements Message ----------------------------------------------

  inline GetVersionInfoResponse* New() const { return New(NULL); }

  GetVersionInfoResponse* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const GetVersionInfoResponse& from);
  void MergeFrom(const GetVersionInfoResponse& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(GetVersionInfoResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string crowdsound_version = 1;
  void clear_crowdsound_version();
  static const int kCrowdsoundVersionFieldNumber = 1;
  const ::std::string& crowdsound_version() const;
  void set_crowdsound_version(const ::std::string& value);
  void set_crowdsound_version(const char* value);
  void set_crowdsound_version(const char* value, size_t size);
  ::std::string* mutable_crowdsound_version();
  ::std::string* release_crowdsound_version();
  void set_allocated_crowdsound_version(::std::string* crowdsound_version);

  // optional string playsource_version = 2;
  void clear_playsource_version();
  static const int kPlaysourceVersionFieldNumber = 2;
  const ::std::string& playsource_version() const;
  void set_playsource_version(const ::std::string& value);
  void set_playsource_version(const char* value);
  void set_playsource_version(const char* value, size_t size);
  ::std::string* mutable_playsource_version();
  ::std::string* release_playsource_version();
  void set_allocated_playsource_version(::std::string* playsource_version);

  // optional string algorithm_version = 3;
  void clear_algorithm_version();
  static const int kAlgorithmVersionFieldNumber = 3;
  const ::std::string& algorithm_version() const;
  void set_algorithm_version(const ::std::string& value);
  void set_algorithm_version(const char* value);
  void set_algorithm_version(const char* value, size_t size);
  ::std::string* mutable_algorithm_version();
  ::std::string* release_algorithm_version();
  void set_allocated_algorithm_version(::std::string* algorithm_version);

  // optional string skrillex_version = 4;
  void clear_skrillex_version();
  static const int kSkrillexVersionFieldNumber = 4;
  const ::std::string& skrillex_version() const;
  void set_skrillex_version(const ::std::string& value);
  void set_skrillex_version(const char* value);
  void set_skrillex_version(const char* value, size_t size);
  ::std::string* mutable_skrillex_version();
  ::std::string* release_skrillex_version();
  void set_allocated_skrillex_version(::std::string* skrillex_version);

  // optional string grpc_version = 5;
  void clear_grpc_version();
  static const int kGrpcVersionFieldNumber = 5;
  const ::std::string& grpc_version() const;
  void set_grpc_version(const ::std::string& value);
  void set_grpc_version(const char* value);
  void set_grpc_version(const char* value, size_t size);
  ::std::string* mutable_grpc_version();
  ::std::string* release_grpc_version();
  void set_allocated_grpc_version(::std::string* grpc_version);

  // @@protoc_insertion_point(class_scope:CrowdSound.GetVersionInfoResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::internal::ArenaStringPtr crowdsound_version_;
  ::google::protobuf::internal::ArenaStringPtr playsource_version_;
  ::google::protobuf::internal::ArenaStringPtr algorithm_version_;
  ::google::protobuf::internal::ArenaStringPtr skrillex_version_;
  ::google::protobuf::internal::ArenaStringPtr grpc_version_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_proto_2fcrowdsound_5fadmin_5fservice_2eproto();
  friend void protobuf_AssignDesc_proto_2fcrowdsound_5fadmin_5fservice_2eproto();
  friend void protobuf_ShutdownFile_proto_2fcrowdsound_5fadmin_5fservice_2eproto();

  void InitAsDefaultInstance();
  static GetVersionInfoResponse* default_instance_;
};
// -------------------------------------------------------------------

class GetDBStatsRequest : public ::google::protobuf::Message {
 public:
  GetDBStatsRequest();
  virtual ~GetDBStatsRequest();

  GetDBStatsRequest(const GetDBStatsRequest& from);

  inline GetDBStatsRequest& operator=(const GetDBStatsRequest& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const GetDBStatsRequest& default_instance();

  void Swap(GetDBStatsRequest* other);

  // implements Message ----------------------------------------------

  inline GetDBStatsRequest* New() const { return New(NULL); }

  GetDBStatsRequest* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const GetDBStatsRequest& from);
  void MergeFrom(const GetDBStatsRequest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(GetDBStatsRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:CrowdSound.GetDBStatsRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_proto_2fcrowdsound_5fadmin_5fservice_2eproto();
  friend void protobuf_AssignDesc_proto_2fcrowdsound_5fadmin_5fservice_2eproto();
  friend void protobuf_ShutdownFile_proto_2fcrowdsound_5fadmin_5fservice_2eproto();

  void InitAsDefaultInstance();
  static GetDBStatsRequest* default_instance_;
};
// -------------------------------------------------------------------

class GetDBStatsResponse : public ::google::protobuf::Message {
 public:
  GetDBStatsResponse();
  virtual ~GetDBStatsResponse();

  GetDBStatsResponse(const GetDBStatsResponse& from);

  inline GetDBStatsResponse& operator=(const GetDBStatsResponse& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const GetDBStatsResponse& default_instance();

  void Swap(GetDBStatsResponse* other);

  // implements Message ----------------------------------------------

  inline GetDBStatsResponse* New() const { return New(NULL); }

  GetDBStatsResponse* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const GetDBStatsResponse& from);
  void MergeFrom(const GetDBStatsResponse& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(GetDBStatsResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 num_songs = 1;
  void clear_num_songs();
  static const int kNumSongsFieldNumber = 1;
  ::google::protobuf::int32 num_songs() const;
  void set_num_songs(::google::protobuf::int32 value);

  // optional int32 num_artists = 2;
  void clear_num_artists();
  static const int kNumArtistsFieldNumber = 2;
  ::google::protobuf::int32 num_artists() const;
  void set_num_artists(::google::protobuf::int32 value);

  // optional int32 num_genres = 3;
  void clear_num_genres();
  static const int kNumGenresFieldNumber = 3;
  ::google::protobuf::int32 num_genres() const;
  void set_num_genres(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:CrowdSound.GetDBStatsResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::int32 num_songs_;
  ::google::protobuf::int32 num_artists_;
  ::google::protobuf::int32 num_genres_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_proto_2fcrowdsound_5fadmin_5fservice_2eproto();
  friend void protobuf_AssignDesc_proto_2fcrowdsound_5fadmin_5fservice_2eproto();
  friend void protobuf_ShutdownFile_proto_2fcrowdsound_5fadmin_5fservice_2eproto();

  void InitAsDefaultInstance();
  static GetDBStatsResponse* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// SkipStatusRequest

// -------------------------------------------------------------------

// SkipStatusResponse

// optional int32 votes_to_skip = 1;
inline void SkipStatusResponse::clear_votes_to_skip() {
  votes_to_skip_ = 0;
}
inline ::google::protobuf::int32 SkipStatusResponse::votes_to_skip() const {
  // @@protoc_insertion_point(field_get:CrowdSound.SkipStatusResponse.votes_to_skip)
  return votes_to_skip_;
}
inline void SkipStatusResponse::set_votes_to_skip(::google::protobuf::int32 value) {
  
  votes_to_skip_ = value;
  // @@protoc_insertion_point(field_set:CrowdSound.SkipStatusResponse.votes_to_skip)
}

// optional int32 total_users = 2;
inline void SkipStatusResponse::clear_total_users() {
  total_users_ = 0;
}
inline ::google::protobuf::int32 SkipStatusResponse::total_users() const {
  // @@protoc_insertion_point(field_get:CrowdSound.SkipStatusResponse.total_users)
  return total_users_;
}
inline void SkipStatusResponse::set_total_users(::google::protobuf::int32 value) {
  
  total_users_ = value;
  // @@protoc_insertion_point(field_set:CrowdSound.SkipStatusResponse.total_users)
}

// optional float threshold = 3;
inline void SkipStatusResponse::clear_threshold() {
  threshold_ = 0;
}
inline float SkipStatusResponse::threshold() const {
  // @@protoc_insertion_point(field_get:CrowdSound.SkipStatusResponse.threshold)
  return threshold_;
}
inline void SkipStatusResponse::set_threshold(float value) {
  
  threshold_ = value;
  // @@protoc_insertion_point(field_set:CrowdSound.SkipStatusResponse.threshold)
}

// -------------------------------------------------------------------

// SkipRequest

// -------------------------------------------------------------------

// SkipResponse

// -------------------------------------------------------------------

// GetSettingsRequest

// -------------------------------------------------------------------

// GetSettingsResponse

// optional bool filter_buffered = 1;
inline void GetSettingsResponse::clear_filter_buffered() {
  filter_buffered_ = false;
}
inline bool GetSettingsResponse::filter_buffered() const {
  // @@protoc_insertion_point(field_get:CrowdSound.GetSettingsResponse.filter_buffered)
  return filter_buffered_;
}
inline void GetSettingsResponse::set_filter_buffered(bool value) {
  
  filter_buffered_ = value;
  // @@protoc_insertion_point(field_set:CrowdSound.GetSettingsResponse.filter_buffered)
}

// optional int32 inactivity_threshold = 2;
inline void GetSettingsResponse::clear_inactivity_threshold() {
  inactivity_threshold_ = 0;
}
inline ::google::protobuf::int32 GetSettingsResponse::inactivity_threshold() const {
  // @@protoc_insertion_point(field_get:CrowdSound.GetSettingsResponse.inactivity_threshold)
  return inactivity_threshold_;
}
inline void GetSettingsResponse::set_inactivity_threshold(::google::protobuf::int32 value) {
  
  inactivity_threshold_ = value;
  // @@protoc_insertion_point(field_set:CrowdSound.GetSettingsResponse.inactivity_threshold)
}

// optional int32 result_limit = 3;
inline void GetSettingsResponse::clear_result_limit() {
  result_limit_ = 0;
}
inline ::google::protobuf::int32 GetSettingsResponse::result_limit() const {
  // @@protoc_insertion_point(field_get:CrowdSound.GetSettingsResponse.result_limit)
  return result_limit_;
}
inline void GetSettingsResponse::set_result_limit(::google::protobuf::int32 value) {
  
  result_limit_ = value;
  // @@protoc_insertion_point(field_set:CrowdSound.GetSettingsResponse.result_limit)
}

// optional string session_name = 4;
inline void GetSettingsResponse::clear_session_name() {
  session_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& GetSettingsResponse::session_name() const {
  // @@protoc_insertion_point(field_get:CrowdSound.GetSettingsResponse.session_name)
  return session_name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GetSettingsResponse::set_session_name(const ::std::string& value) {
  
  session_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:CrowdSound.GetSettingsResponse.session_name)
}
inline void GetSettingsResponse::set_session_name(const char* value) {
  
  session_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:CrowdSound.GetSettingsResponse.session_name)
}
inline void GetSettingsResponse::set_session_name(const char* value, size_t size) {
  
  session_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:CrowdSound.GetSettingsResponse.session_name)
}
inline ::std::string* GetSettingsResponse::mutable_session_name() {
  
  // @@protoc_insertion_point(field_mutable:CrowdSound.GetSettingsResponse.session_name)
  return session_name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* GetSettingsResponse::release_session_name() {
  
  return session_name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GetSettingsResponse::set_allocated_session_name(::std::string* session_name) {
  if (session_name != NULL) {
    
  } else {
    
  }
  session_name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), session_name);
  // @@protoc_insertion_point(field_set_allocated:CrowdSound.GetSettingsResponse.session_name)
}

// optional int32 queue_size = 5;
inline void GetSettingsResponse::clear_queue_size() {
  queue_size_ = 0;
}
inline ::google::protobuf::int32 GetSettingsResponse::queue_size() const {
  // @@protoc_insertion_point(field_get:CrowdSound.GetSettingsResponse.queue_size)
  return queue_size_;
}
inline void GetSettingsResponse::set_queue_size(::google::protobuf::int32 value) {
  
  queue_size_ = value;
  // @@protoc_insertion_point(field_set:CrowdSound.GetSettingsResponse.queue_size)
}

// optional int32 trending_artists_size = 6;
inline void GetSettingsResponse::clear_trending_artists_size() {
  trending_artists_size_ = 0;
}
inline ::google::protobuf::int32 GetSettingsResponse::trending_artists_size() const {
  // @@protoc_insertion_point(field_get:CrowdSound.GetSettingsResponse.trending_artists_size)
  return trending_artists_size_;
}
inline void GetSettingsResponse::set_trending_artists_size(::google::protobuf::int32 value) {
  
  trending_artists_size_ = value;
  // @@protoc_insertion_point(field_set:CrowdSound.GetSettingsResponse.trending_artists_size)
}

// optional float skip_threshold = 7;
inline void GetSettingsResponse::clear_skip_threshold() {
  skip_threshold_ = 0;
}
inline float GetSettingsResponse::skip_threshold() const {
  // @@protoc_insertion_point(field_get:CrowdSound.GetSettingsResponse.skip_threshold)
  return skip_threshold_;
}
inline void GetSettingsResponse::set_skip_threshold(float value) {
  
  skip_threshold_ = value;
  // @@protoc_insertion_point(field_set:CrowdSound.GetSettingsResponse.skip_threshold)
}

// optional float count_weight = 8;
inline void GetSettingsResponse::clear_count_weight() {
  count_weight_ = 0;
}
inline float GetSettingsResponse::count_weight() const {
  // @@protoc_insertion_point(field_get:CrowdSound.GetSettingsResponse.count_weight)
  return count_weight_;
}
inline void GetSettingsResponse::set_count_weight(float value) {
  
  count_weight_ = value;
  // @@protoc_insertion_point(field_set:CrowdSound.GetSettingsResponse.count_weight)
}

// optional float vote_weight = 9;
inline void GetSettingsResponse::clear_vote_weight() {
  vote_weight_ = 0;
}
inline float GetSettingsResponse::vote_weight() const {
  // @@protoc_insertion_point(field_get:CrowdSound.GetSettingsResponse.vote_weight)
  return vote_weight_;
}
inline void GetSettingsResponse::set_vote_weight(float value) {
  
  vote_weight_ = value;
  // @@protoc_insertion_point(field_set:CrowdSound.GetSettingsResponse.vote_weight)
}

// optional float genre_weight = 10;
inline void GetSettingsResponse::clear_genre_weight() {
  genre_weight_ = 0;
}
inline float GetSettingsResponse::genre_weight() const {
  // @@protoc_insertion_point(field_get:CrowdSound.GetSettingsResponse.genre_weight)
  return genre_weight_;
}
inline void GetSettingsResponse::set_genre_weight(float value) {
  
  genre_weight_ = value;
  // @@protoc_insertion_point(field_set:CrowdSound.GetSettingsResponse.genre_weight)
}

// optional float artist_weight = 11;
inline void GetSettingsResponse::clear_artist_weight() {
  artist_weight_ = 0;
}
inline float GetSettingsResponse::artist_weight() const {
  // @@protoc_insertion_point(field_get:CrowdSound.GetSettingsResponse.artist_weight)
  return artist_weight_;
}
inline void GetSettingsResponse::set_artist_weight(float value) {
  
  artist_weight_ = value;
  // @@protoc_insertion_point(field_set:CrowdSound.GetSettingsResponse.artist_weight)
}

// optional float played_again_mult = 12;
inline void GetSettingsResponse::clear_played_again_mult() {
  played_again_mult_ = 0;
}
inline float GetSettingsResponse::played_again_mult() const {
  // @@protoc_insertion_point(field_get:CrowdSound.GetSettingsResponse.played_again_mult)
  return played_again_mult_;
}
inline void GetSettingsResponse::set_played_again_mult(float value) {
  
  played_again_mult_ = value;
  // @@protoc_insertion_point(field_set:CrowdSound.GetSettingsResponse.played_again_mult)
}

// optional float min_repeat_window = 13;
inline void GetSettingsResponse::clear_min_repeat_window() {
  min_repeat_window_ = 0;
}
inline float GetSettingsResponse::min_repeat_window() const {
  // @@protoc_insertion_point(field_get:CrowdSound.GetSettingsResponse.min_repeat_window)
  return min_repeat_window_;
}
inline void GetSettingsResponse::set_min_repeat_window(float value) {
  
  min_repeat_window_ = value;
  // @@protoc_insertion_point(field_set:CrowdSound.GetSettingsResponse.min_repeat_window)
}

// -------------------------------------------------------------------

// SetSettingRequest

// optional string key = 1;
inline void SetSettingRequest::clear_key() {
  key_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& SetSettingRequest::key() const {
  // @@protoc_insertion_point(field_get:CrowdSound.SetSettingRequest.key)
  return key_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void SetSettingRequest::set_key(const ::std::string& value) {
  
  key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:CrowdSound.SetSettingRequest.key)
}
inline void SetSettingRequest::set_key(const char* value) {
  
  key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:CrowdSound.SetSettingRequest.key)
}
inline void SetSettingRequest::set_key(const char* value, size_t size) {
  
  key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:CrowdSound.SetSettingRequest.key)
}
inline ::std::string* SetSettingRequest::mutable_key() {
  
  // @@protoc_insertion_point(field_mutable:CrowdSound.SetSettingRequest.key)
  return key_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* SetSettingRequest::release_key() {
  
  return key_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void SetSettingRequest::set_allocated_key(::std::string* key) {
  if (key != NULL) {
    
  } else {
    
  }
  key_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), key);
  // @@protoc_insertion_point(field_set_allocated:CrowdSound.SetSettingRequest.key)
}

// optional bool bool_val = 2;
inline bool SetSettingRequest::has_bool_val() const {
  return value_case() == kBoolVal;
}
inline void SetSettingRequest::set_has_bool_val() {
  _oneof_case_[0] = kBoolVal;
}
inline void SetSettingRequest::clear_bool_val() {
  if (has_bool_val()) {
    value_.bool_val_ = false;
    clear_has_value();
  }
}
inline bool SetSettingRequest::bool_val() const {
  // @@protoc_insertion_point(field_get:CrowdSound.SetSettingRequest.bool_val)
  if (has_bool_val()) {
    return value_.bool_val_;
  }
  return false;
}
inline void SetSettingRequest::set_bool_val(bool value) {
  if (!has_bool_val()) {
    clear_value();
    set_has_bool_val();
  }
  value_.bool_val_ = value;
  // @@protoc_insertion_point(field_set:CrowdSound.SetSettingRequest.bool_val)
}

// optional string str_val = 3;
inline bool SetSettingRequest::has_str_val() const {
  return value_case() == kStrVal;
}
inline void SetSettingRequest::set_has_str_val() {
  _oneof_case_[0] = kStrVal;
}
inline void SetSettingRequest::clear_str_val() {
  if (has_str_val()) {
    value_.str_val_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    clear_has_value();
  }
}
inline const ::std::string& SetSettingRequest::str_val() const {
  // @@protoc_insertion_point(field_get:CrowdSound.SetSettingRequest.str_val)
  if (has_str_val()) {
    return value_.str_val_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  return *&::google::protobuf::internal::GetEmptyStringAlreadyInited();
}
inline void SetSettingRequest::set_str_val(const ::std::string& value) {
  // @@protoc_insertion_point(field_set:CrowdSound.SetSettingRequest.str_val)
  if (!has_str_val()) {
    clear_value();
    set_has_str_val();
    value_.str_val_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  value_.str_val_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:CrowdSound.SetSettingRequest.str_val)
}
inline void SetSettingRequest::set_str_val(const char* value) {
  if (!has_str_val()) {
    clear_value();
    set_has_str_val();
    value_.str_val_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  value_.str_val_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(value));
  // @@protoc_insertion_point(field_set_char:CrowdSound.SetSettingRequest.str_val)
}
inline void SetSettingRequest::set_str_val(const char* value, size_t size) {
  if (!has_str_val()) {
    clear_value();
    set_has_str_val();
    value_.str_val_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  value_.str_val_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:CrowdSound.SetSettingRequest.str_val)
}
inline ::std::string* SetSettingRequest::mutable_str_val() {
  if (!has_str_val()) {
    clear_value();
    set_has_str_val();
    value_.str_val_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_mutable:CrowdSound.SetSettingRequest.str_val)
  return value_.str_val_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* SetSettingRequest::release_str_val() {
  if (has_str_val()) {
    clear_has_value();
    return value_.str_val_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  } else {
    return NULL;
  }
}
inline void SetSettingRequest::set_allocated_str_val(::std::string* str_val) {
  if (!has_str_val()) {
    value_.str_val_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  clear_value();
  if (str_val != NULL) {
    set_has_str_val();
    value_.str_val_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
        str_val);
  }
  // @@protoc_insertion_point(field_set_allocated:CrowdSound.SetSettingRequest.str_val)
}

// optional int32 int_val = 4;
inline bool SetSettingRequest::has_int_val() const {
  return value_case() == kIntVal;
}
inline void SetSettingRequest::set_has_int_val() {
  _oneof_case_[0] = kIntVal;
}
inline void SetSettingRequest::clear_int_val() {
  if (has_int_val()) {
    value_.int_val_ = 0;
    clear_has_value();
  }
}
inline ::google::protobuf::int32 SetSettingRequest::int_val() const {
  // @@protoc_insertion_point(field_get:CrowdSound.SetSettingRequest.int_val)
  if (has_int_val()) {
    return value_.int_val_;
  }
  return 0;
}
inline void SetSettingRequest::set_int_val(::google::protobuf::int32 value) {
  if (!has_int_val()) {
    clear_value();
    set_has_int_val();
  }
  value_.int_val_ = value;
  // @@protoc_insertion_point(field_set:CrowdSound.SetSettingRequest.int_val)
}

// optional float float_val = 5;
inline bool SetSettingRequest::has_float_val() const {
  return value_case() == kFloatVal;
}
inline void SetSettingRequest::set_has_float_val() {
  _oneof_case_[0] = kFloatVal;
}
inline void SetSettingRequest::clear_float_val() {
  if (has_float_val()) {
    value_.float_val_ = 0;
    clear_has_value();
  }
}
inline float SetSettingRequest::float_val() const {
  // @@protoc_insertion_point(field_get:CrowdSound.SetSettingRequest.float_val)
  if (has_float_val()) {
    return value_.float_val_;
  }
  return 0;
}
inline void SetSettingRequest::set_float_val(float value) {
  if (!has_float_val()) {
    clear_value();
    set_has_float_val();
  }
  value_.float_val_ = value;
  // @@protoc_insertion_point(field_set:CrowdSound.SetSettingRequest.float_val)
}

inline bool SetSettingRequest::has_value() const {
  return value_case() != VALUE_NOT_SET;
}
inline void SetSettingRequest::clear_has_value() {
  _oneof_case_[0] = VALUE_NOT_SET;
}
inline SetSettingRequest::ValueCase SetSettingRequest::value_case() const {
  return SetSettingRequest::ValueCase(_oneof_case_[0]);
}
// -------------------------------------------------------------------

// SetSettingResponse

// -------------------------------------------------------------------

// GetVersionInfoRequest

// -------------------------------------------------------------------

// GetVersionInfoResponse

// optional string crowdsound_version = 1;
inline void GetVersionInfoResponse::clear_crowdsound_version() {
  crowdsound_version_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& GetVersionInfoResponse::crowdsound_version() const {
  // @@protoc_insertion_point(field_get:CrowdSound.GetVersionInfoResponse.crowdsound_version)
  return crowdsound_version_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GetVersionInfoResponse::set_crowdsound_version(const ::std::string& value) {
  
  crowdsound_version_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:CrowdSound.GetVersionInfoResponse.crowdsound_version)
}
inline void GetVersionInfoResponse::set_crowdsound_version(const char* value) {
  
  crowdsound_version_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:CrowdSound.GetVersionInfoResponse.crowdsound_version)
}
inline void GetVersionInfoResponse::set_crowdsound_version(const char* value, size_t size) {
  
  crowdsound_version_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:CrowdSound.GetVersionInfoResponse.crowdsound_version)
}
inline ::std::string* GetVersionInfoResponse::mutable_crowdsound_version() {
  
  // @@protoc_insertion_point(field_mutable:CrowdSound.GetVersionInfoResponse.crowdsound_version)
  return crowdsound_version_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* GetVersionInfoResponse::release_crowdsound_version() {
  
  return crowdsound_version_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GetVersionInfoResponse::set_allocated_crowdsound_version(::std::string* crowdsound_version) {
  if (crowdsound_version != NULL) {
    
  } else {
    
  }
  crowdsound_version_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), crowdsound_version);
  // @@protoc_insertion_point(field_set_allocated:CrowdSound.GetVersionInfoResponse.crowdsound_version)
}

// optional string playsource_version = 2;
inline void GetVersionInfoResponse::clear_playsource_version() {
  playsource_version_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& GetVersionInfoResponse::playsource_version() const {
  // @@protoc_insertion_point(field_get:CrowdSound.GetVersionInfoResponse.playsource_version)
  return playsource_version_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GetVersionInfoResponse::set_playsource_version(const ::std::string& value) {
  
  playsource_version_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:CrowdSound.GetVersionInfoResponse.playsource_version)
}
inline void GetVersionInfoResponse::set_playsource_version(const char* value) {
  
  playsource_version_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:CrowdSound.GetVersionInfoResponse.playsource_version)
}
inline void GetVersionInfoResponse::set_playsource_version(const char* value, size_t size) {
  
  playsource_version_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:CrowdSound.GetVersionInfoResponse.playsource_version)
}
inline ::std::string* GetVersionInfoResponse::mutable_playsource_version() {
  
  // @@protoc_insertion_point(field_mutable:CrowdSound.GetVersionInfoResponse.playsource_version)
  return playsource_version_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* GetVersionInfoResponse::release_playsource_version() {
  
  return playsource_version_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GetVersionInfoResponse::set_allocated_playsource_version(::std::string* playsource_version) {
  if (playsource_version != NULL) {
    
  } else {
    
  }
  playsource_version_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), playsource_version);
  // @@protoc_insertion_point(field_set_allocated:CrowdSound.GetVersionInfoResponse.playsource_version)
}

// optional string algorithm_version = 3;
inline void GetVersionInfoResponse::clear_algorithm_version() {
  algorithm_version_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& GetVersionInfoResponse::algorithm_version() const {
  // @@protoc_insertion_point(field_get:CrowdSound.GetVersionInfoResponse.algorithm_version)
  return algorithm_version_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GetVersionInfoResponse::set_algorithm_version(const ::std::string& value) {
  
  algorithm_version_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:CrowdSound.GetVersionInfoResponse.algorithm_version)
}
inline void GetVersionInfoResponse::set_algorithm_version(const char* value) {
  
  algorithm_version_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:CrowdSound.GetVersionInfoResponse.algorithm_version)
}
inline void GetVersionInfoResponse::set_algorithm_version(const char* value, size_t size) {
  
  algorithm_version_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:CrowdSound.GetVersionInfoResponse.algorithm_version)
}
inline ::std::string* GetVersionInfoResponse::mutable_algorithm_version() {
  
  // @@protoc_insertion_point(field_mutable:CrowdSound.GetVersionInfoResponse.algorithm_version)
  return algorithm_version_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* GetVersionInfoResponse::release_algorithm_version() {
  
  return algorithm_version_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GetVersionInfoResponse::set_allocated_algorithm_version(::std::string* algorithm_version) {
  if (algorithm_version != NULL) {
    
  } else {
    
  }
  algorithm_version_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), algorithm_version);
  // @@protoc_insertion_point(field_set_allocated:CrowdSound.GetVersionInfoResponse.algorithm_version)
}

// optional string skrillex_version = 4;
inline void GetVersionInfoResponse::clear_skrillex_version() {
  skrillex_version_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& GetVersionInfoResponse::skrillex_version() const {
  // @@protoc_insertion_point(field_get:CrowdSound.GetVersionInfoResponse.skrillex_version)
  return skrillex_version_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GetVersionInfoResponse::set_skrillex_version(const ::std::string& value) {
  
  skrillex_version_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:CrowdSound.GetVersionInfoResponse.skrillex_version)
}
inline void GetVersionInfoResponse::set_skrillex_version(const char* value) {
  
  skrillex_version_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:CrowdSound.GetVersionInfoResponse.skrillex_version)
}
inline void GetVersionInfoResponse::set_skrillex_version(const char* value, size_t size) {
  
  skrillex_version_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:CrowdSound.GetVersionInfoResponse.skrillex_version)
}
inline ::std::string* GetVersionInfoResponse::mutable_skrillex_version() {
  
  // @@protoc_insertion_point(field_mutable:CrowdSound.GetVersionInfoResponse.skrillex_version)
  return skrillex_version_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* GetVersionInfoResponse::release_skrillex_version() {
  
  return skrillex_version_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GetVersionInfoResponse::set_allocated_skrillex_version(::std::string* skrillex_version) {
  if (skrillex_version != NULL) {
    
  } else {
    
  }
  skrillex_version_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), skrillex_version);
  // @@protoc_insertion_point(field_set_allocated:CrowdSound.GetVersionInfoResponse.skrillex_version)
}

// optional string grpc_version = 5;
inline void GetVersionInfoResponse::clear_grpc_version() {
  grpc_version_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& GetVersionInfoResponse::grpc_version() const {
  // @@protoc_insertion_point(field_get:CrowdSound.GetVersionInfoResponse.grpc_version)
  return grpc_version_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GetVersionInfoResponse::set_grpc_version(const ::std::string& value) {
  
  grpc_version_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:CrowdSound.GetVersionInfoResponse.grpc_version)
}
inline void GetVersionInfoResponse::set_grpc_version(const char* value) {
  
  grpc_version_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:CrowdSound.GetVersionInfoResponse.grpc_version)
}
inline void GetVersionInfoResponse::set_grpc_version(const char* value, size_t size) {
  
  grpc_version_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:CrowdSound.GetVersionInfoResponse.grpc_version)
}
inline ::std::string* GetVersionInfoResponse::mutable_grpc_version() {
  
  // @@protoc_insertion_point(field_mutable:CrowdSound.GetVersionInfoResponse.grpc_version)
  return grpc_version_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* GetVersionInfoResponse::release_grpc_version() {
  
  return grpc_version_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GetVersionInfoResponse::set_allocated_grpc_version(::std::string* grpc_version) {
  if (grpc_version != NULL) {
    
  } else {
    
  }
  grpc_version_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), grpc_version);
  // @@protoc_insertion_point(field_set_allocated:CrowdSound.GetVersionInfoResponse.grpc_version)
}

// -------------------------------------------------------------------

// GetDBStatsRequest

// -------------------------------------------------------------------

// GetDBStatsResponse

// optional int32 num_songs = 1;
inline void GetDBStatsResponse::clear_num_songs() {
  num_songs_ = 0;
}
inline ::google::protobuf::int32 GetDBStatsResponse::num_songs() const {
  // @@protoc_insertion_point(field_get:CrowdSound.GetDBStatsResponse.num_songs)
  return num_songs_;
}
inline void GetDBStatsResponse::set_num_songs(::google::protobuf::int32 value) {
  
  num_songs_ = value;
  // @@protoc_insertion_point(field_set:CrowdSound.GetDBStatsResponse.num_songs)
}

// optional int32 num_artists = 2;
inline void GetDBStatsResponse::clear_num_artists() {
  num_artists_ = 0;
}
inline ::google::protobuf::int32 GetDBStatsResponse::num_artists() const {
  // @@protoc_insertion_point(field_get:CrowdSound.GetDBStatsResponse.num_artists)
  return num_artists_;
}
inline void GetDBStatsResponse::set_num_artists(::google::protobuf::int32 value) {
  
  num_artists_ = value;
  // @@protoc_insertion_point(field_set:CrowdSound.GetDBStatsResponse.num_artists)
}

// optional int32 num_genres = 3;
inline void GetDBStatsResponse::clear_num_genres() {
  num_genres_ = 0;
}
inline ::google::protobuf::int32 GetDBStatsResponse::num_genres() const {
  // @@protoc_insertion_point(field_get:CrowdSound.GetDBStatsResponse.num_genres)
  return num_genres_;
}
inline void GetDBStatsResponse::set_num_genres(::google::protobuf::int32 value) {
  
  num_genres_ = value;
  // @@protoc_insertion_point(field_set:CrowdSound.GetDBStatsResponse.num_genres)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace CrowdSound

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_proto_2fcrowdsound_5fadmin_5fservice_2eproto__INCLUDED
