// Generated by the gRPC protobuf plugin.
// If you make any local change, they will be lost.
// source: proto/crowdsound_service.proto
#ifndef GRPC_proto_2fcrowdsound_5fservice_2eproto__INCLUDED
#define GRPC_proto_2fcrowdsound_5fservice_2eproto__INCLUDED

#include "proto/crowdsound_service.pb.h"

#include <grpc++/support/async_stream.h>
#include <grpc++/impl/rpc_method.h>
#include <grpc++/impl/proto_utils.h>
#include <grpc++/impl/service_type.h>
#include <grpc++/support/async_unary_call.h>
#include <grpc++/support/status.h>
#include <grpc++/support/stub_options.h>
#include <grpc++/support/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class RpcService;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace CrowdSound {

class CrowdSound GRPC_FINAL {
 public:
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status Ping(::grpc::ClientContext* context, const ::CrowdSound::PingRequest& request, ::CrowdSound::PingResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::CrowdSound::PingResponse>> AsyncPing(::grpc::ClientContext* context, const ::CrowdSound::PingRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::CrowdSound::PingResponse>>(AsyncPingRaw(context, request, cq));
    }
    virtual ::grpc::Status GetSessionData(::grpc::ClientContext* context, const ::CrowdSound::GetSessionDataRequest& request, ::CrowdSound::GetSessionDataResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::CrowdSound::GetSessionDataResponse>> AsyncGetSessionData(::grpc::ClientContext* context, const ::CrowdSound::GetSessionDataRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::CrowdSound::GetSessionDataResponse>>(AsyncGetSessionDataRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientReaderInterface< ::CrowdSound::GetQueueResponse>> GetQueue(::grpc::ClientContext* context, const ::CrowdSound::GetQueueRequest& request) {
      return std::unique_ptr< ::grpc::ClientReaderInterface< ::CrowdSound::GetQueueResponse>>(GetQueueRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::CrowdSound::GetQueueResponse>> AsyncGetQueue(::grpc::ClientContext* context, const ::CrowdSound::GetQueueRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::CrowdSound::GetQueueResponse>>(AsyncGetQueueRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientReaderInterface< ::CrowdSound::ListTrendingArtistsResponse>> ListTrendingArtists(::grpc::ClientContext* context, const ::CrowdSound::ListTrendingArtistsRequest& request) {
      return std::unique_ptr< ::grpc::ClientReaderInterface< ::CrowdSound::ListTrendingArtistsResponse>>(ListTrendingArtistsRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::CrowdSound::ListTrendingArtistsResponse>> AsyncListTrendingArtists(::grpc::ClientContext* context, const ::CrowdSound::ListTrendingArtistsRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::CrowdSound::ListTrendingArtistsResponse>>(AsyncListTrendingArtistsRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientWriterInterface< ::CrowdSound::PostSongRequest>> PostSong(::grpc::ClientContext* context, ::CrowdSound::PostSongResponse* response) {
      return std::unique_ptr< ::grpc::ClientWriterInterface< ::CrowdSound::PostSongRequest>>(PostSongRaw(context, response));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::CrowdSound::PostSongRequest>> AsyncPostSong(::grpc::ClientContext* context, ::CrowdSound::PostSongResponse* response, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::CrowdSound::PostSongRequest>>(AsyncPostSongRaw(context, response, cq, tag));
    }
    virtual ::grpc::Status VoteSong(::grpc::ClientContext* context, const ::CrowdSound::VoteSongRequest& request, ::CrowdSound::VoteSongResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::CrowdSound::VoteSongResponse>> AsyncVoteSong(::grpc::ClientContext* context, const ::CrowdSound::VoteSongRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::CrowdSound::VoteSongResponse>>(AsyncVoteSongRaw(context, request, cq));
    }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::CrowdSound::PingResponse>* AsyncPingRaw(::grpc::ClientContext* context, const ::CrowdSound::PingRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::CrowdSound::GetSessionDataResponse>* AsyncGetSessionDataRaw(::grpc::ClientContext* context, const ::CrowdSound::GetSessionDataRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientReaderInterface< ::CrowdSound::GetQueueResponse>* GetQueueRaw(::grpc::ClientContext* context, const ::CrowdSound::GetQueueRequest& request) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::CrowdSound::GetQueueResponse>* AsyncGetQueueRaw(::grpc::ClientContext* context, const ::CrowdSound::GetQueueRequest& request, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientReaderInterface< ::CrowdSound::ListTrendingArtistsResponse>* ListTrendingArtistsRaw(::grpc::ClientContext* context, const ::CrowdSound::ListTrendingArtistsRequest& request) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::CrowdSound::ListTrendingArtistsResponse>* AsyncListTrendingArtistsRaw(::grpc::ClientContext* context, const ::CrowdSound::ListTrendingArtistsRequest& request, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientWriterInterface< ::CrowdSound::PostSongRequest>* PostSongRaw(::grpc::ClientContext* context, ::CrowdSound::PostSongResponse* response) = 0;
    virtual ::grpc::ClientAsyncWriterInterface< ::CrowdSound::PostSongRequest>* AsyncPostSongRaw(::grpc::ClientContext* context, ::CrowdSound::PostSongResponse* response, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::CrowdSound::VoteSongResponse>* AsyncVoteSongRaw(::grpc::ClientContext* context, const ::CrowdSound::VoteSongRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub GRPC_FINAL : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::Channel>& channel);
    ::grpc::Status Ping(::grpc::ClientContext* context, const ::CrowdSound::PingRequest& request, ::CrowdSound::PingResponse* response) GRPC_OVERRIDE;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::CrowdSound::PingResponse>> AsyncPing(::grpc::ClientContext* context, const ::CrowdSound::PingRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::CrowdSound::PingResponse>>(AsyncPingRaw(context, request, cq));
    }
    ::grpc::Status GetSessionData(::grpc::ClientContext* context, const ::CrowdSound::GetSessionDataRequest& request, ::CrowdSound::GetSessionDataResponse* response) GRPC_OVERRIDE;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::CrowdSound::GetSessionDataResponse>> AsyncGetSessionData(::grpc::ClientContext* context, const ::CrowdSound::GetSessionDataRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::CrowdSound::GetSessionDataResponse>>(AsyncGetSessionDataRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientReader< ::CrowdSound::GetQueueResponse>> GetQueue(::grpc::ClientContext* context, const ::CrowdSound::GetQueueRequest& request) {
      return std::unique_ptr< ::grpc::ClientReader< ::CrowdSound::GetQueueResponse>>(GetQueueRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::CrowdSound::GetQueueResponse>> AsyncGetQueue(::grpc::ClientContext* context, const ::CrowdSound::GetQueueRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::CrowdSound::GetQueueResponse>>(AsyncGetQueueRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientReader< ::CrowdSound::ListTrendingArtistsResponse>> ListTrendingArtists(::grpc::ClientContext* context, const ::CrowdSound::ListTrendingArtistsRequest& request) {
      return std::unique_ptr< ::grpc::ClientReader< ::CrowdSound::ListTrendingArtistsResponse>>(ListTrendingArtistsRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::CrowdSound::ListTrendingArtistsResponse>> AsyncListTrendingArtists(::grpc::ClientContext* context, const ::CrowdSound::ListTrendingArtistsRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::CrowdSound::ListTrendingArtistsResponse>>(AsyncListTrendingArtistsRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientWriter< ::CrowdSound::PostSongRequest>> PostSong(::grpc::ClientContext* context, ::CrowdSound::PostSongResponse* response) {
      return std::unique_ptr< ::grpc::ClientWriter< ::CrowdSound::PostSongRequest>>(PostSongRaw(context, response));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriter< ::CrowdSound::PostSongRequest>> AsyncPostSong(::grpc::ClientContext* context, ::CrowdSound::PostSongResponse* response, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncWriter< ::CrowdSound::PostSongRequest>>(AsyncPostSongRaw(context, response, cq, tag));
    }
    ::grpc::Status VoteSong(::grpc::ClientContext* context, const ::CrowdSound::VoteSongRequest& request, ::CrowdSound::VoteSongResponse* response) GRPC_OVERRIDE;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::CrowdSound::VoteSongResponse>> AsyncVoteSong(::grpc::ClientContext* context, const ::CrowdSound::VoteSongRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::CrowdSound::VoteSongResponse>>(AsyncVoteSongRaw(context, request, cq));
    }

   private:
    std::shared_ptr< ::grpc::Channel> channel_;
    ::grpc::ClientAsyncResponseReader< ::CrowdSound::PingResponse>* AsyncPingRaw(::grpc::ClientContext* context, const ::CrowdSound::PingRequest& request, ::grpc::CompletionQueue* cq) GRPC_OVERRIDE;
    ::grpc::ClientAsyncResponseReader< ::CrowdSound::GetSessionDataResponse>* AsyncGetSessionDataRaw(::grpc::ClientContext* context, const ::CrowdSound::GetSessionDataRequest& request, ::grpc::CompletionQueue* cq) GRPC_OVERRIDE;
    ::grpc::ClientReader< ::CrowdSound::GetQueueResponse>* GetQueueRaw(::grpc::ClientContext* context, const ::CrowdSound::GetQueueRequest& request) GRPC_OVERRIDE;
    ::grpc::ClientAsyncReader< ::CrowdSound::GetQueueResponse>* AsyncGetQueueRaw(::grpc::ClientContext* context, const ::CrowdSound::GetQueueRequest& request, ::grpc::CompletionQueue* cq, void* tag) GRPC_OVERRIDE;
    ::grpc::ClientReader< ::CrowdSound::ListTrendingArtistsResponse>* ListTrendingArtistsRaw(::grpc::ClientContext* context, const ::CrowdSound::ListTrendingArtistsRequest& request) GRPC_OVERRIDE;
    ::grpc::ClientAsyncReader< ::CrowdSound::ListTrendingArtistsResponse>* AsyncListTrendingArtistsRaw(::grpc::ClientContext* context, const ::CrowdSound::ListTrendingArtistsRequest& request, ::grpc::CompletionQueue* cq, void* tag) GRPC_OVERRIDE;
    ::grpc::ClientWriter< ::CrowdSound::PostSongRequest>* PostSongRaw(::grpc::ClientContext* context, ::CrowdSound::PostSongResponse* response) GRPC_OVERRIDE;
    ::grpc::ClientAsyncWriter< ::CrowdSound::PostSongRequest>* AsyncPostSongRaw(::grpc::ClientContext* context, ::CrowdSound::PostSongResponse* response, ::grpc::CompletionQueue* cq, void* tag) GRPC_OVERRIDE;
    ::grpc::ClientAsyncResponseReader< ::CrowdSound::VoteSongResponse>* AsyncVoteSongRaw(::grpc::ClientContext* context, const ::CrowdSound::VoteSongRequest& request, ::grpc::CompletionQueue* cq) GRPC_OVERRIDE;
    const ::grpc::RpcMethod rpcmethod_Ping_;
    const ::grpc::RpcMethod rpcmethod_GetSessionData_;
    const ::grpc::RpcMethod rpcmethod_GetQueue_;
    const ::grpc::RpcMethod rpcmethod_ListTrendingArtists_;
    const ::grpc::RpcMethod rpcmethod_PostSong_;
    const ::grpc::RpcMethod rpcmethod_VoteSong_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::Channel>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::SynchronousService {
   public:
    Service() : service_(nullptr) {}
    virtual ~Service();
    virtual ::grpc::Status Ping(::grpc::ServerContext* context, const ::CrowdSound::PingRequest* request, ::CrowdSound::PingResponse* response);
    virtual ::grpc::Status GetSessionData(::grpc::ServerContext* context, const ::CrowdSound::GetSessionDataRequest* request, ::CrowdSound::GetSessionDataResponse* response);
    virtual ::grpc::Status GetQueue(::grpc::ServerContext* context, const ::CrowdSound::GetQueueRequest* request, ::grpc::ServerWriter< ::CrowdSound::GetQueueResponse>* writer);
    virtual ::grpc::Status ListTrendingArtists(::grpc::ServerContext* context, const ::CrowdSound::ListTrendingArtistsRequest* request, ::grpc::ServerWriter< ::CrowdSound::ListTrendingArtistsResponse>* writer);
    virtual ::grpc::Status PostSong(::grpc::ServerContext* context, ::grpc::ServerReader< ::CrowdSound::PostSongRequest>* reader, ::CrowdSound::PostSongResponse* response);
    virtual ::grpc::Status VoteSong(::grpc::ServerContext* context, const ::CrowdSound::VoteSongRequest* request, ::CrowdSound::VoteSongResponse* response);
    ::grpc::RpcService* service() GRPC_OVERRIDE GRPC_FINAL;
   private:
    ::grpc::RpcService* service_;
  };
  class AsyncService GRPC_FINAL : public ::grpc::AsynchronousService {
   public:
    explicit AsyncService();
    ~AsyncService() {};
    void RequestPing(::grpc::ServerContext* context, ::CrowdSound::PingRequest* request, ::grpc::ServerAsyncResponseWriter< ::CrowdSound::PingResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag);
    void RequestGetSessionData(::grpc::ServerContext* context, ::CrowdSound::GetSessionDataRequest* request, ::grpc::ServerAsyncResponseWriter< ::CrowdSound::GetSessionDataResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag);
    void RequestGetQueue(::grpc::ServerContext* context, ::CrowdSound::GetQueueRequest* request, ::grpc::ServerAsyncWriter< ::CrowdSound::GetQueueResponse>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag);
    void RequestListTrendingArtists(::grpc::ServerContext* context, ::CrowdSound::ListTrendingArtistsRequest* request, ::grpc::ServerAsyncWriter< ::CrowdSound::ListTrendingArtistsResponse>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag);
    void RequestPostSong(::grpc::ServerContext* context, ::grpc::ServerAsyncReader< ::CrowdSound::PostSongResponse, ::CrowdSound::PostSongRequest>* reader, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag);
    void RequestVoteSong(::grpc::ServerContext* context, ::CrowdSound::VoteSongRequest* request, ::grpc::ServerAsyncResponseWriter< ::CrowdSound::VoteSongResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag);
  };
};

}  // namespace CrowdSound


#endif  // GRPC_proto_2fcrowdsound_5fservice_2eproto__INCLUDED
