// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/crowdsound_service.proto

#ifndef PROTOBUF_proto_2fcrowdsound_5fservice_2eproto__INCLUDED
#define PROTOBUF_proto_2fcrowdsound_5fservice_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace CrowdSound {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_proto_2fcrowdsound_5fservice_2eproto();
void protobuf_AssignDesc_proto_2fcrowdsound_5fservice_2eproto();
void protobuf_ShutdownFile_proto_2fcrowdsound_5fservice_2eproto();

class ListSongsRequest;
class ListSongsResponse;
class ListTrendingArtistsRequest;
class ListTrendingArtistsResponse;
class PostSongRequest;
class PostSongResponse;
class VoteSongRequest;
class VoteSongResponse;

// ===================================================================

class ListSongsRequest : public ::google::protobuf::Message {
 public:
  ListSongsRequest();
  virtual ~ListSongsRequest();

  ListSongsRequest(const ListSongsRequest& from);

  inline ListSongsRequest& operator=(const ListSongsRequest& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ListSongsRequest& default_instance();

  void Swap(ListSongsRequest* other);

  // implements Message ----------------------------------------------

  inline ListSongsRequest* New() const { return New(NULL); }

  ListSongsRequest* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ListSongsRequest& from);
  void MergeFrom(const ListSongsRequest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ListSongsRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:CrowdSound.ListSongsRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_proto_2fcrowdsound_5fservice_2eproto();
  friend void protobuf_AssignDesc_proto_2fcrowdsound_5fservice_2eproto();
  friend void protobuf_ShutdownFile_proto_2fcrowdsound_5fservice_2eproto();

  void InitAsDefaultInstance();
  static ListSongsRequest* default_instance_;
};
// -------------------------------------------------------------------

class ListSongsResponse : public ::google::protobuf::Message {
 public:
  ListSongsResponse();
  virtual ~ListSongsResponse();

  ListSongsResponse(const ListSongsResponse& from);

  inline ListSongsResponse& operator=(const ListSongsResponse& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ListSongsResponse& default_instance();

  void Swap(ListSongsResponse* other);

  // implements Message ----------------------------------------------

  inline ListSongsResponse* New() const { return New(NULL); }

  ListSongsResponse* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ListSongsResponse& from);
  void MergeFrom(const ListSongsResponse& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ListSongsResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string name = 1;
  void clear_name();
  static const int kNameFieldNumber = 1;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // optional bool isPlaying = 2;
  void clear_isplaying();
  static const int kIsPlayingFieldNumber = 2;
  bool isplaying() const;
  void set_isplaying(bool value);

  // @@protoc_insertion_point(class_scope:CrowdSound.ListSongsResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  bool isplaying_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_proto_2fcrowdsound_5fservice_2eproto();
  friend void protobuf_AssignDesc_proto_2fcrowdsound_5fservice_2eproto();
  friend void protobuf_ShutdownFile_proto_2fcrowdsound_5fservice_2eproto();

  void InitAsDefaultInstance();
  static ListSongsResponse* default_instance_;
};
// -------------------------------------------------------------------

class ListTrendingArtistsRequest : public ::google::protobuf::Message {
 public:
  ListTrendingArtistsRequest();
  virtual ~ListTrendingArtistsRequest();

  ListTrendingArtistsRequest(const ListTrendingArtistsRequest& from);

  inline ListTrendingArtistsRequest& operator=(const ListTrendingArtistsRequest& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ListTrendingArtistsRequest& default_instance();

  void Swap(ListTrendingArtistsRequest* other);

  // implements Message ----------------------------------------------

  inline ListTrendingArtistsRequest* New() const { return New(NULL); }

  ListTrendingArtistsRequest* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ListTrendingArtistsRequest& from);
  void MergeFrom(const ListTrendingArtistsRequest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ListTrendingArtistsRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:CrowdSound.ListTrendingArtistsRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_proto_2fcrowdsound_5fservice_2eproto();
  friend void protobuf_AssignDesc_proto_2fcrowdsound_5fservice_2eproto();
  friend void protobuf_ShutdownFile_proto_2fcrowdsound_5fservice_2eproto();

  void InitAsDefaultInstance();
  static ListTrendingArtistsRequest* default_instance_;
};
// -------------------------------------------------------------------

class ListTrendingArtistsResponse : public ::google::protobuf::Message {
 public:
  ListTrendingArtistsResponse();
  virtual ~ListTrendingArtistsResponse();

  ListTrendingArtistsResponse(const ListTrendingArtistsResponse& from);

  inline ListTrendingArtistsResponse& operator=(const ListTrendingArtistsResponse& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ListTrendingArtistsResponse& default_instance();

  void Swap(ListTrendingArtistsResponse* other);

  // implements Message ----------------------------------------------

  inline ListTrendingArtistsResponse* New() const { return New(NULL); }

  ListTrendingArtistsResponse* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ListTrendingArtistsResponse& from);
  void MergeFrom(const ListTrendingArtistsResponse& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ListTrendingArtistsResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string name = 1;
  void clear_name();
  static const int kNameFieldNumber = 1;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // optional int32 score = 2;
  void clear_score();
  static const int kScoreFieldNumber = 2;
  ::google::protobuf::int32 score() const;
  void set_score(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:CrowdSound.ListTrendingArtistsResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::google::protobuf::int32 score_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_proto_2fcrowdsound_5fservice_2eproto();
  friend void protobuf_AssignDesc_proto_2fcrowdsound_5fservice_2eproto();
  friend void protobuf_ShutdownFile_proto_2fcrowdsound_5fservice_2eproto();

  void InitAsDefaultInstance();
  static ListTrendingArtistsResponse* default_instance_;
};
// -------------------------------------------------------------------

class PostSongRequest : public ::google::protobuf::Message {
 public:
  PostSongRequest();
  virtual ~PostSongRequest();

  PostSongRequest(const PostSongRequest& from);

  inline PostSongRequest& operator=(const PostSongRequest& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PostSongRequest& default_instance();

  void Swap(PostSongRequest* other);

  // implements Message ----------------------------------------------

  inline PostSongRequest* New() const { return New(NULL); }

  PostSongRequest* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PostSongRequest& from);
  void MergeFrom(const PostSongRequest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(PostSongRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string name = 1;
  void clear_name();
  static const int kNameFieldNumber = 1;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // optional string artist = 2;
  void clear_artist();
  static const int kArtistFieldNumber = 2;
  const ::std::string& artist() const;
  void set_artist(const ::std::string& value);
  void set_artist(const char* value);
  void set_artist(const char* value, size_t size);
  ::std::string* mutable_artist();
  ::std::string* release_artist();
  void set_allocated_artist(::std::string* artist);

  // optional string genre = 3;
  void clear_genre();
  static const int kGenreFieldNumber = 3;
  const ::std::string& genre() const;
  void set_genre(const ::std::string& value);
  void set_genre(const char* value);
  void set_genre(const char* value, size_t size);
  ::std::string* mutable_genre();
  ::std::string* release_genre();
  void set_allocated_genre(::std::string* genre);

  // @@protoc_insertion_point(class_scope:CrowdSound.PostSongRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::google::protobuf::internal::ArenaStringPtr artist_;
  ::google::protobuf::internal::ArenaStringPtr genre_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_proto_2fcrowdsound_5fservice_2eproto();
  friend void protobuf_AssignDesc_proto_2fcrowdsound_5fservice_2eproto();
  friend void protobuf_ShutdownFile_proto_2fcrowdsound_5fservice_2eproto();

  void InitAsDefaultInstance();
  static PostSongRequest* default_instance_;
};
// -------------------------------------------------------------------

class PostSongResponse : public ::google::protobuf::Message {
 public:
  PostSongResponse();
  virtual ~PostSongResponse();

  PostSongResponse(const PostSongResponse& from);

  inline PostSongResponse& operator=(const PostSongResponse& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PostSongResponse& default_instance();

  void Swap(PostSongResponse* other);

  // implements Message ----------------------------------------------

  inline PostSongResponse* New() const { return New(NULL); }

  PostSongResponse* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PostSongResponse& from);
  void MergeFrom(const PostSongResponse& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(PostSongResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:CrowdSound.PostSongResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_proto_2fcrowdsound_5fservice_2eproto();
  friend void protobuf_AssignDesc_proto_2fcrowdsound_5fservice_2eproto();
  friend void protobuf_ShutdownFile_proto_2fcrowdsound_5fservice_2eproto();

  void InitAsDefaultInstance();
  static PostSongResponse* default_instance_;
};
// -------------------------------------------------------------------

class VoteSongRequest : public ::google::protobuf::Message {
 public:
  VoteSongRequest();
  virtual ~VoteSongRequest();

  VoteSongRequest(const VoteSongRequest& from);

  inline VoteSongRequest& operator=(const VoteSongRequest& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const VoteSongRequest& default_instance();

  void Swap(VoteSongRequest* other);

  // implements Message ----------------------------------------------

  inline VoteSongRequest* New() const { return New(NULL); }

  VoteSongRequest* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const VoteSongRequest& from);
  void MergeFrom(const VoteSongRequest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(VoteSongRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string name = 1;
  void clear_name();
  static const int kNameFieldNumber = 1;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // optional string artist = 2;
  void clear_artist();
  static const int kArtistFieldNumber = 2;
  const ::std::string& artist() const;
  void set_artist(const ::std::string& value);
  void set_artist(const char* value);
  void set_artist(const char* value, size_t size);
  ::std::string* mutable_artist();
  ::std::string* release_artist();
  void set_allocated_artist(::std::string* artist);

  // optional bool like = 3;
  void clear_like();
  static const int kLikeFieldNumber = 3;
  bool like() const;
  void set_like(bool value);

  // @@protoc_insertion_point(class_scope:CrowdSound.VoteSongRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::google::protobuf::internal::ArenaStringPtr artist_;
  bool like_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_proto_2fcrowdsound_5fservice_2eproto();
  friend void protobuf_AssignDesc_proto_2fcrowdsound_5fservice_2eproto();
  friend void protobuf_ShutdownFile_proto_2fcrowdsound_5fservice_2eproto();

  void InitAsDefaultInstance();
  static VoteSongRequest* default_instance_;
};
// -------------------------------------------------------------------

class VoteSongResponse : public ::google::protobuf::Message {
 public:
  VoteSongResponse();
  virtual ~VoteSongResponse();

  VoteSongResponse(const VoteSongResponse& from);

  inline VoteSongResponse& operator=(const VoteSongResponse& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const VoteSongResponse& default_instance();

  void Swap(VoteSongResponse* other);

  // implements Message ----------------------------------------------

  inline VoteSongResponse* New() const { return New(NULL); }

  VoteSongResponse* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const VoteSongResponse& from);
  void MergeFrom(const VoteSongResponse& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(VoteSongResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:CrowdSound.VoteSongResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_proto_2fcrowdsound_5fservice_2eproto();
  friend void protobuf_AssignDesc_proto_2fcrowdsound_5fservice_2eproto();
  friend void protobuf_ShutdownFile_proto_2fcrowdsound_5fservice_2eproto();

  void InitAsDefaultInstance();
  static VoteSongResponse* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// ListSongsRequest

// -------------------------------------------------------------------

// ListSongsResponse

// optional string name = 1;
inline void ListSongsResponse::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ListSongsResponse::name() const {
  // @@protoc_insertion_point(field_get:CrowdSound.ListSongsResponse.name)
  return name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ListSongsResponse::set_name(const ::std::string& value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:CrowdSound.ListSongsResponse.name)
}
inline void ListSongsResponse::set_name(const char* value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:CrowdSound.ListSongsResponse.name)
}
inline void ListSongsResponse::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:CrowdSound.ListSongsResponse.name)
}
inline ::std::string* ListSongsResponse::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:CrowdSound.ListSongsResponse.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ListSongsResponse::release_name() {
  
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ListSongsResponse::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:CrowdSound.ListSongsResponse.name)
}

// optional bool isPlaying = 2;
inline void ListSongsResponse::clear_isplaying() {
  isplaying_ = false;
}
inline bool ListSongsResponse::isplaying() const {
  // @@protoc_insertion_point(field_get:CrowdSound.ListSongsResponse.isPlaying)
  return isplaying_;
}
inline void ListSongsResponse::set_isplaying(bool value) {
  
  isplaying_ = value;
  // @@protoc_insertion_point(field_set:CrowdSound.ListSongsResponse.isPlaying)
}

// -------------------------------------------------------------------

// ListTrendingArtistsRequest

// -------------------------------------------------------------------

// ListTrendingArtistsResponse

// optional string name = 1;
inline void ListTrendingArtistsResponse::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ListTrendingArtistsResponse::name() const {
  // @@protoc_insertion_point(field_get:CrowdSound.ListTrendingArtistsResponse.name)
  return name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ListTrendingArtistsResponse::set_name(const ::std::string& value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:CrowdSound.ListTrendingArtistsResponse.name)
}
inline void ListTrendingArtistsResponse::set_name(const char* value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:CrowdSound.ListTrendingArtistsResponse.name)
}
inline void ListTrendingArtistsResponse::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:CrowdSound.ListTrendingArtistsResponse.name)
}
inline ::std::string* ListTrendingArtistsResponse::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:CrowdSound.ListTrendingArtistsResponse.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ListTrendingArtistsResponse::release_name() {
  
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ListTrendingArtistsResponse::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:CrowdSound.ListTrendingArtistsResponse.name)
}

// optional int32 score = 2;
inline void ListTrendingArtistsResponse::clear_score() {
  score_ = 0;
}
inline ::google::protobuf::int32 ListTrendingArtistsResponse::score() const {
  // @@protoc_insertion_point(field_get:CrowdSound.ListTrendingArtistsResponse.score)
  return score_;
}
inline void ListTrendingArtistsResponse::set_score(::google::protobuf::int32 value) {
  
  score_ = value;
  // @@protoc_insertion_point(field_set:CrowdSound.ListTrendingArtistsResponse.score)
}

// -------------------------------------------------------------------

// PostSongRequest

// optional string name = 1;
inline void PostSongRequest::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& PostSongRequest::name() const {
  // @@protoc_insertion_point(field_get:CrowdSound.PostSongRequest.name)
  return name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void PostSongRequest::set_name(const ::std::string& value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:CrowdSound.PostSongRequest.name)
}
inline void PostSongRequest::set_name(const char* value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:CrowdSound.PostSongRequest.name)
}
inline void PostSongRequest::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:CrowdSound.PostSongRequest.name)
}
inline ::std::string* PostSongRequest::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:CrowdSound.PostSongRequest.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* PostSongRequest::release_name() {
  
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void PostSongRequest::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:CrowdSound.PostSongRequest.name)
}

// optional string artist = 2;
inline void PostSongRequest::clear_artist() {
  artist_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& PostSongRequest::artist() const {
  // @@protoc_insertion_point(field_get:CrowdSound.PostSongRequest.artist)
  return artist_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void PostSongRequest::set_artist(const ::std::string& value) {
  
  artist_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:CrowdSound.PostSongRequest.artist)
}
inline void PostSongRequest::set_artist(const char* value) {
  
  artist_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:CrowdSound.PostSongRequest.artist)
}
inline void PostSongRequest::set_artist(const char* value, size_t size) {
  
  artist_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:CrowdSound.PostSongRequest.artist)
}
inline ::std::string* PostSongRequest::mutable_artist() {
  
  // @@protoc_insertion_point(field_mutable:CrowdSound.PostSongRequest.artist)
  return artist_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* PostSongRequest::release_artist() {
  
  return artist_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void PostSongRequest::set_allocated_artist(::std::string* artist) {
  if (artist != NULL) {
    
  } else {
    
  }
  artist_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), artist);
  // @@protoc_insertion_point(field_set_allocated:CrowdSound.PostSongRequest.artist)
}

// optional string genre = 3;
inline void PostSongRequest::clear_genre() {
  genre_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& PostSongRequest::genre() const {
  // @@protoc_insertion_point(field_get:CrowdSound.PostSongRequest.genre)
  return genre_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void PostSongRequest::set_genre(const ::std::string& value) {
  
  genre_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:CrowdSound.PostSongRequest.genre)
}
inline void PostSongRequest::set_genre(const char* value) {
  
  genre_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:CrowdSound.PostSongRequest.genre)
}
inline void PostSongRequest::set_genre(const char* value, size_t size) {
  
  genre_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:CrowdSound.PostSongRequest.genre)
}
inline ::std::string* PostSongRequest::mutable_genre() {
  
  // @@protoc_insertion_point(field_mutable:CrowdSound.PostSongRequest.genre)
  return genre_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* PostSongRequest::release_genre() {
  
  return genre_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void PostSongRequest::set_allocated_genre(::std::string* genre) {
  if (genre != NULL) {
    
  } else {
    
  }
  genre_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), genre);
  // @@protoc_insertion_point(field_set_allocated:CrowdSound.PostSongRequest.genre)
}

// -------------------------------------------------------------------

// PostSongResponse

// -------------------------------------------------------------------

// VoteSongRequest

// optional string name = 1;
inline void VoteSongRequest::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& VoteSongRequest::name() const {
  // @@protoc_insertion_point(field_get:CrowdSound.VoteSongRequest.name)
  return name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void VoteSongRequest::set_name(const ::std::string& value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:CrowdSound.VoteSongRequest.name)
}
inline void VoteSongRequest::set_name(const char* value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:CrowdSound.VoteSongRequest.name)
}
inline void VoteSongRequest::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:CrowdSound.VoteSongRequest.name)
}
inline ::std::string* VoteSongRequest::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:CrowdSound.VoteSongRequest.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* VoteSongRequest::release_name() {
  
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void VoteSongRequest::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:CrowdSound.VoteSongRequest.name)
}

// optional string artist = 2;
inline void VoteSongRequest::clear_artist() {
  artist_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& VoteSongRequest::artist() const {
  // @@protoc_insertion_point(field_get:CrowdSound.VoteSongRequest.artist)
  return artist_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void VoteSongRequest::set_artist(const ::std::string& value) {
  
  artist_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:CrowdSound.VoteSongRequest.artist)
}
inline void VoteSongRequest::set_artist(const char* value) {
  
  artist_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:CrowdSound.VoteSongRequest.artist)
}
inline void VoteSongRequest::set_artist(const char* value, size_t size) {
  
  artist_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:CrowdSound.VoteSongRequest.artist)
}
inline ::std::string* VoteSongRequest::mutable_artist() {
  
  // @@protoc_insertion_point(field_mutable:CrowdSound.VoteSongRequest.artist)
  return artist_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* VoteSongRequest::release_artist() {
  
  return artist_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void VoteSongRequest::set_allocated_artist(::std::string* artist) {
  if (artist != NULL) {
    
  } else {
    
  }
  artist_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), artist);
  // @@protoc_insertion_point(field_set_allocated:CrowdSound.VoteSongRequest.artist)
}

// optional bool like = 3;
inline void VoteSongRequest::clear_like() {
  like_ = false;
}
inline bool VoteSongRequest::like() const {
  // @@protoc_insertion_point(field_get:CrowdSound.VoteSongRequest.like)
  return like_;
}
inline void VoteSongRequest::set_like(bool value) {
  
  like_ = value;
  // @@protoc_insertion_point(field_set:CrowdSound.VoteSongRequest.like)
}

// -------------------------------------------------------------------

// VoteSongResponse

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace CrowdSound

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_proto_2fcrowdsound_5fservice_2eproto__INCLUDED
