// GENERATED BY version.py
#ifndef version_hpp
#define version_hpp

#include <string>

const std::string CROWDSOUND_VERSION = "ee466e8";
const std::string PLAYSOURCE_VERSION = "a3c9473";
const std::string ALGORITHM_VERSION  = "faf464c";
const std::string SKRILLEX_VERSION   = "48bfe14";
const std::string GRPC_VERSION       = "0.11-1";

#endif
